version: 2

sources:
  - name: dwhpublic
    database: dwh
    schema: public
    tables:
      - name: data
      - name: tbl_georef
  - name: dwhexternal
    database: dwh
    schema: external
    tables:
      - name: hist_odoo_res_company
      - name: hist_odoo_res_partner
      - name: hist_odoo_cm_place
      - name: hist_odoo_cm_presenter_model
      - name: hist_odoo_energy_selfconsumption_selfconsumption
      - name: hist_odoo_crm_team
      - name: hist_odoo_res_company_res_partner_rel
      - name: hist_odoo_landing_page
      - name: hist_odoo_crm_lead